name: Java CI - Build
permissions:
  contents: read
on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build with Gradle
        run: ./gradlew shadowJar